import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import { ProjectContentProvider } from "./components/ProjectContentContext";
import Navigation from "./components/navigation";
import InfoContainer from "./components/infoContainer";
import { Syne } from "next/font/google";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-(--bisqueware) text-(--kiln-fire)`}
      >
        <main className="fixed w-screen h-screen overflow-hidden">
          <ProjectContentProvider>
            <ViewTransitions>
              <Navigation />
              <InfoContainer />
              {children}
            </ViewTransitions>
          </ProjectContentProvider>
        </main>
      </body>
    </html>
  );
}
